// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUD-0sAu4NrIBDLbu3Q7PkLCnZlUcXN0',
    appId: '1:355023214318:web:531ae3a4e66f888dc1c5ff',
    messagingSenderId: '355023214318',
    projectId: 'push-notification-9b805',
    authDomain: 'push-notification-9b805.firebaseapp.com',
    storageBucket: 'push-notification-9b805.appspot.com',
    measurementId: 'G-YLEQ5WNBWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIUSXWNBXdtSz0sV2zjCSb9sHZv4VX2gc',
    appId: '1:355023214318:android:fe33d268d90c9e39c1c5ff',
    messagingSenderId: '355023214318',
    projectId: 'push-notification-9b805',
    storageBucket: 'push-notification-9b805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVvBBgltFBkAF1SZLfctsI69KSB9CjvE',
    appId: '1:355023214318:ios:c0a2701a60e34237c1c5ff',
    messagingSenderId: '355023214318',
    projectId: 'push-notification-9b805',
    storageBucket: 'push-notification-9b805.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVVvBBgltFBkAF1SZLfctsI69KSB9CjvE',
    appId: '1:355023214318:ios:c0a2701a60e34237c1c5ff',
    messagingSenderId: '355023214318',
    projectId: 'push-notification-9b805',
    storageBucket: 'push-notification-9b805.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwUD-0sAu4NrIBDLbu3Q7PkLCnZlUcXN0',
    appId: '1:355023214318:web:d0f6d59d91eb80aec1c5ff',
    messagingSenderId: '355023214318',
    projectId: 'push-notification-9b805',
    authDomain: 'push-notification-9b805.firebaseapp.com',
    storageBucket: 'push-notification-9b805.appspot.com',
    measurementId: 'G-TYR6JKV8V0',
  );
}
